title: test-docs-workflow Documentation
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

# Navigation
nav:
  - Home: index.md
  - Technical Documentation: technical/index.md
  - Business Documentation: business/index.md 